package com.google.android.gms.internal;

import android.os.Parcel;
import com.google.android.gms.common.internal.safeparcel.SafeParcelable;
import com.google.android.gms.fitness.FitnessActivities;
import com.google.android.gms.games.multiplayer.Multiplayer;

public final class oa implements SafeParcelable {
    public static final ob CREATOR;
    public static final oa ahB;
    public static final oa ahC;
    public static final oa ahD;
    public static final oa ahE;
    public static final oa ahF;
    public static final oa ahG;
    public static final oa ahH;
    public static final oa ahI;
    public static final oa ahJ;
    public static final oa ahK;
    public static final oa ahL;
    public static final oa ahM;
    public static final oa ahN;
    public static final oa ahO;
    public static final oa ahP;
    public static final oa ahQ;
    public static final oa ahR;
    public static final oa ahS;
    public static final oa ahT;
    public static final oa ahU;
    public static final oa ahV;
    public static final oa ahW;
    public static final oa ahX;
    public static final oa ahY;
    public static final oa ahZ;
    public static final oa aiA;
    public static final oa aiB;
    public static final oa aiC;
    public static final oa aiD;
    public static final oa aiE;
    public static final oa aiF;
    public static final oa aiG;
    public static final oa aiH;
    public static final oa aiI;
    public static final oa aiJ;
    public static final oa aiK;
    public static final oa aiL;
    public static final oa aiM;
    public static final oa aiN;
    public static final oa aiO;
    public static final oa aiP;
    public static final oa aiQ;
    public static final oa aiR;
    public static final oa aiS;
    public static final oa aiT;
    public static final oa aiU;
    public static final oa aiV;
    public static final oa aiW;
    public static final oa aiX;
    public static final oa aiY;
    public static final oa aiZ;
    public static final oa aia;
    public static final oa aib;
    public static final oa aic;
    public static final oa aid;
    public static final oa aie;
    public static final oa aif;
    public static final oa aig;
    public static final oa aih;
    public static final oa aii;
    public static final oa aij;
    public static final oa aik;
    public static final oa ail;
    public static final oa aim;
    public static final oa ain;
    public static final oa aio;
    public static final oa aip;
    public static final oa aiq;
    public static final oa air;
    public static final oa ais;
    public static final oa ait;
    public static final oa aiu;
    public static final oa aiv;
    public static final oa aiw;
    public static final oa aix;
    public static final oa aiy;
    public static final oa aiz;
    public static final oa ajA;
    public static final oa ajB;
    public static final oa ajC;
    public static final oa ajD;
    public static final oa ajE;
    public static final oa ajF;
    public static final oa ajG;
    public static final oa ajH;
    public static final oa ajI;
    public static final oa ajJ;
    public static final oa ajK;
    public static final oa ajL;
    public static final oa ajM;
    public static final oa ajN;
    public static final oa ajO;
    public static final oa ajP;
    public static final oa ajQ;
    public static final oa ajR;
    public static final oa ajS;
    public static final oa ajT;
    public static final oa ajU;
    public static final oa ajV;
    public static final oa ajW;
    public static final oa aja;
    public static final oa ajb;
    public static final oa ajc;
    public static final oa ajd;
    public static final oa aje;
    public static final oa ajf;
    public static final oa ajg;
    public static final oa ajh;
    public static final oa aji;
    public static final oa ajj;
    public static final oa ajk;
    public static final oa ajl;
    public static final oa ajm;
    public static final oa ajn;
    public static final oa ajo;
    public static final oa ajp;
    public static final oa ajq;
    public static final oa ajr;
    public static final oa ajs;
    public static final oa ajt;
    public static final oa aju;
    public static final oa ajv;
    public static final oa ajw;
    public static final oa ajx;
    public static final oa ajy;
    public static final oa ajz;
    final int CK;
    final String vc;

    static {
        ahB = cc("accounting");
        ahC = cc("airport");
        ahD = cc("amusement_park");
        ahE = cc("aquarium");
        ahF = cc("art_gallery");
        ahG = cc("atm");
        ahH = cc("bakery");
        ahI = cc("bank");
        ahJ = cc("bar");
        ahK = cc("beauty_salon");
        ahL = cc("bicycle_store");
        ahM = cc("book_store");
        ahN = cc("bowling_alley");
        ahO = cc("bus_station");
        ahP = cc("cafe");
        ahQ = cc("campground");
        ahR = cc("car_dealer");
        ahS = cc("car_rental");
        ahT = cc("car_repair");
        ahU = cc("car_wash");
        ahV = cc("casino");
        ahW = cc("cemetery");
        ahX = cc("church");
        ahY = cc("city_hall");
        ahZ = cc("clothing_store");
        aia = cc("convenience_store");
        aib = cc("courthouse");
        aic = cc("dentist");
        aid = cc("department_store");
        aie = cc("doctor");
        aif = cc("electrician");
        aig = cc("electronics_store");
        aih = cc("embassy");
        aii = cc("establishment");
        aij = cc("finance");
        aik = cc("fire_station");
        ail = cc("florist");
        aim = cc("food");
        ain = cc("funeral_home");
        aio = cc("furniture_store");
        aip = cc("gas_station");
        aiq = cc("general_contractor");
        air = cc("grocery_or_supermarket");
        ais = cc("gym");
        ait = cc("hair_care");
        aiu = cc("hardware_store");
        aiv = cc("health");
        aiw = cc("hindu_temple");
        aix = cc("home_goods_store");
        aiy = cc("hospital");
        aiz = cc("insurance_agency");
        aiA = cc("jewelry_store");
        aiB = cc("laundry");
        aiC = cc("lawyer");
        aiD = cc("library");
        aiE = cc("liquor_store");
        aiF = cc("local_government_office");
        aiG = cc("locksmith");
        aiH = cc("lodging");
        aiI = cc("meal_delivery");
        aiJ = cc("meal_takeaway");
        aiK = cc("mosque");
        aiL = cc("movie_rental");
        aiM = cc("movie_theater");
        aiN = cc("moving_company");
        aiO = cc("museum");
        aiP = cc("night_club");
        aiQ = cc("painter");
        aiR = cc("park");
        aiS = cc("parking");
        aiT = cc("pet_store");
        aiU = cc("pharmacy");
        aiV = cc("physiotherapist");
        aiW = cc("place_of_worship");
        aiX = cc("plumber");
        aiY = cc("police");
        aiZ = cc("post_office");
        aja = cc("real_estate_agency");
        ajb = cc("restaurant");
        ajc = cc("roofing_contractor");
        ajd = cc("rv_park");
        aje = cc("school");
        ajf = cc("shoe_store");
        ajg = cc("shopping_mall");
        ajh = cc("spa");
        aji = cc("stadium");
        ajj = cc("storage");
        ajk = cc("store");
        ajl = cc("subway_station");
        ajm = cc("synagogue");
        ajn = cc("taxi_stand");
        ajo = cc("train_station");
        ajp = cc("travel_agency");
        ajq = cc("university");
        ajr = cc("veterinary_care");
        ajs = cc("zoo");
        ajt = cc("administrative_area_level_1");
        aju = cc("administrative_area_level_2");
        ajv = cc("administrative_area_level_3");
        ajw = cc("colloquial_area");
        ajx = cc("country");
        ajy = cc("floor");
        ajz = cc("geocode");
        ajA = cc("intersection");
        ajB = cc("locality");
        ajC = cc("natural_feature");
        ajD = cc("neighborhood");
        ajE = cc("political");
        ajF = cc("point_of_interest");
        ajG = cc("post_box");
        ajH = cc("postal_code");
        ajI = cc("postal_code_prefix");
        ajJ = cc("postal_town");
        ajK = cc("premise");
        ajL = cc(Multiplayer.EXTRA_ROOM);
        ajM = cc("route");
        ajN = cc("street_address");
        ajO = cc("sublocality");
        ajP = cc("sublocality_level_1");
        ajQ = cc("sublocality_level_2");
        ajR = cc("sublocality_level_3");
        ajS = cc("sublocality_level_4");
        ajT = cc("sublocality_level_5");
        ajU = cc("subpremise");
        ajV = cc("transit_station");
        ajW = cc(FitnessActivities.OTHER);
        CREATOR = new ob();
    }

    oa(int i, String str) {
        jx.bb(str);
        this.CK = i;
        this.vc = str;
    }

    public static oa cc(String str) {
        return new oa(0, str);
    }

    public final int describeContents() {
        ob obVar = CREATOR;
        return 0;
    }

    public final boolean equals(Object obj) {
        return (obj instanceof oa) && this.vc.equals(((oa) obj).vc);
    }

    public final int hashCode() {
        return this.vc.hashCode();
    }

    public final String toString() {
        return this.vc;
    }

    public final void writeToParcel(Parcel parcel, int i) {
        ob obVar = CREATOR;
        ob.m5688a(this, parcel, i);
    }
}
